services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api:/var/www/api
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/ssl_certificate.cer:/etc/ssl_certificate.cer
      - ./ssl/_private-key.key:/etc/_private-key.key
    depends_on:
      - server
    networks:
      - server
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
  server:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - server
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production

networks:
  server:
    driver: bridge
